<div class="page_blog">
<?php $posts = $this->getPosts(); ?>
<?php foreach ($posts as $post): ?>
<div class="postWrapper">
    <div class="postTitle">
        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a></h2>
        <h3><?php echo $post->getCreatedTime(); ?></h3>
    </div>
    <div class="postContent"><?php echo $post->getPostContent(); ?></div>
    
    <?php echo $this->getBookmarkHtml($post) ?>
    <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
    <div class="postDetails">
        <?php if($this->getCommentsEnabled()): ?>
        <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> | 
        <?php endif; ?>
        <?php $postCats = $post->getCats(); ?>
        <?php echo Mage::helper('blog')->__('Posted');?>
        <?php echo$this->__("By");?> <?php echo $post->getUser(); ?></div>
</div>
<?php endforeach; ?> 
<?php $this->getPages(); ?>
</div>