<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Productrelater
 * @copyright  Copyright (c) 2003-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php if($this->getCount()>0) : ?>
<?php $pro = $this->getProduct();?>
<div class="box base-mini mini-related-items aw-arp-block">
    <div class="head">
        <h4 class="relatename head-des"><?php echo $pro->getSku().' '. $this->getBlockName() ?></h4>
    </div>
    <div class="content aw-arp-content">
        <?php foreach ($this->getItems() as $item) : ?>
            <div class="aw-arp-item">
                <a href="<?php echo $item->getProductUrl()?>">
                    <?php echo $this->htmlEscape($item->getSku())?>
                    <?php echo $this->htmlEscape($item->getName())?>
                </a>
            </div>
        <?php endforeach; ?>
        <div class="clear"></div>
    </div>
</div>
<style type="text/css">
.aw-arp-block{ display:inline-block;width:100%; padding:5px 0;}
.relatename{  color: #fff;  font-size: 12px;  font-weight: bold;  }
.aw-arp-content{padding: 0 10px;}
.aw-arp-item {float: none;  line-height: 28px;  width: auto;  text-align: left; background:url(<?php echo $this->getUrl()?>/skin/frontend/lead2pass/default/images/amy/group-1.gif) no-repeat left center;    padding-left: 15px; }
.aw-arp-item a{  color: #666666;  font-size: 12px;  text-decoration: none;  }
.aw-arp-item a:hover {  color: #27905D;  text-decoration: underline;  }
</style>
<?php endif; ?>