 
<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()){?> 
<div class="block block-login">  
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post">
        <div class="block-content">
            <label for="mini-login"><?php echo $this->__('Email:') ?></label><input type="text" name="login[username]" id="mini-login" class="input-text" />
            <label for="mini-password"><?php echo $this->__('Password:') ?></label><input type="password" name="login[password]" id="mini-password" class="input-text" />            
        </div>
		<div class="actions">
				<a class="forget-min-login" href="<?php echo $this->getForgotPasswordUrl() ?>"></a>
                <button type="submit" class="button min-login-btn"></button>
        </div>
    </form>
	</div>
<?php }else{	?>
<div class="login_in_show">
	<p class="wel_cus">Welcome <?php echo Mage::getSingleton('customer/session')->getCustomer()->getEmail();?></p>
	<a href="<?php echo $this->getUrl()?>customer/account/" class="accountimg"></a>
	<a href="<?php echo $this->getUrl()?>customer/account/logout/" class="loginoutimg"></a>
</div>
<?php	}?>



