<div class="hotcert" id="hotcert">
    
		<?php
		$categories_ids = array(370,163,148,139);
		
		$formId_cats = array();
		foreach($categories_ids as $get_id){
			$formId_cats[] =  Mage::getModel('catalog/category')->load($get_id);
		}
		
		
		foreach ($formId_cats as $category) {
		
			if ($category->getIsActive()) {
		?>
		<div class="hotspot">
		<div class="hotcert_t">		
		 <span class="fr">
		<?php			
				// get all children
				if (Mage::helper('catalog/category_flat')->isEnabled()) {
					$children = (array)$category->getChildrenNodes();
					$childrenCount = count($children);
				} else {
					$children = $category->getChildrenCategories();
					$childrenCount = $children->count();
				}
				
				// select active children
				
				$i=0;
				foreach ($children as $child) {
					if ($child->getIsActive()&&$i<3) {
					echo '<a href="'.$this->getCategoryUrl($child).'">'.$this->htmlEscape($child->getName()).'</a> | ';
					}
					$i++;
				}				
			?>
			<a href="<?php echo $this->getCategoryUrl($category)?>" class="hot_more">More</a>
		</span>
		<span class="hot_t"><?php echo $this->htmlEscape($category->getName());?></span>
	</div>
	</div>
	
	<?php 
	 $categoryId = $category->getId();
	 $category = Mage::getModel('catalog/category')->load($categoryId);
	 $resource = Mage::getSingleton('core/resource');
		$read = $resource->getConnection('catalog_read');
		$categoryProductTable = $resource->getTableName('catalog/category_product');
		$categoryTable = $resource->getTableName('catalog_category_entity');
		$productEntityIntTable = (string)Mage::getConfig()->getTablePrefix() . 'catalog_product_entity_int';
		$eavAttributeTable = $resource->getTableName('eav/attribute');
		$select_subcat = $read->select()
		                      ->from(array('cat'=>$categoryTable))
							  ->where('cat.path LIKE ?',$category->getPath().'/%')
							  ;
		$subcategories = $read->fetchAll($select_subcat);
		$subcatids = array();
		if(!empty($subcategories)):
			foreach( $subcategories as $subcategory ):
			$subcatids[] = $subcategory['entity_id'];
			endforeach;
		endif;
		array_push($subcatids,$categoryId);
					   
		$select = $read->select()
					   ->from(array('cp'=>$categoryProductTable))
					   ->join(array('pei'=>$productEntityIntTable), 'pei.entity_id=cp.product_id', array())
					   ->joinNatural(array('ea'=>$eavAttributeTable))
					   ->where('cp.category_id IN(?)', $subcatids)
					   ->where('pei.value=1')
					   ->where('ea.attribute_code="hot_product"');

					   $rows = $read->fetchAll($select);
		$ids = array();

		foreach($rows AS $row) {
		  $ids[] = $row['product_id'];
		}
		$ret = implode(",", $ids);
		$collection = Mage::getModel('catalog/product')->getCollection();
	  $collection->getSelect()->where("e.entity_id in (?)", $ids);
	  $collection->addAttributeToSelect(array('name','sku','url_key'));
	  $collection->setOrder('SKU','asc');
	  $productList = $collection->load();
	  $count_hotproduct = count($productList);
	  if($count_hotproduct){
	  echo '<ul>';
	  	foreach( $productList as $product_hot):
	      echo '<li><a href="'.$product_hot->getProductUrl().'">'.$product_hot->getSku().'</a></li>';
	 	endforeach;
	  echo '</ul>';
	  }
	  
	 ?>
	


<?php		
	}
}
?>

</div>